# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VM_BOX = "centos/7"

cluster = {
  "control-machine" => {
    :ip => "192.168.33.10", :cpus => 1, :mem => 256, :synced_folder => true, :port_forward => false
  },
  "zk1" => {
    :ip => "192.168.33.11", :cpus => 1, :mem => 256, :synced_folder => false, :port_forward => true
  },
  "zk2" => {
    :ip => "192.168.33.12", :cpus => 1, :mem => 256, :synced_folder => false, :port_forward => false
  },
  "zk3" => {
    :ip => "192.168.33.13", :cpus => 1, :mem => 256, :synced_folder => false, :port_forward => false
  },
  "broker1" => {
    :ip => "192.168.33.21", :cpus => 2, :mem => 1024, :synced_folder => false, :port_forward => false
  },
  "broker2" => {
    :ip => "192.168.33.22", :cpus => 2, :mem => 1024, :synced_folder => false, :port_forward => false
  },
  "broker3" => {
    :ip => "192.168.33.23", :cpus => 2, :mem => 1024, :synced_folder => false, :port_forward => false
  },
}

# All Vagrant configuration is done below.
# The "2" in Vagrant.configure configures the configuration version
# (we support older styles for backwards compatability).
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = VM_BOX
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
        if info[:synced_folder]
          override.vm.synced_folder "..", "/pulsar-ansible",
            mount_options: ["dmode=775,fmode=664"]
          override.vm.provision "shell", inline: <<-SHELL
            yum update -y
            yum install -y kernel-devel kernel-headers
            yum install -y wget vim yum-utils gcc-c++ device-mapper-persistent-data lvm2
          SHELL
        end # end if `synced_folder`
        if info[:port_forward]
          override.vm.network "forwarded_port", guest: 9090, host: 9090, auto_correct: true
          override.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
        end # end if `port_forword`
      end # end provider
    end # end config
  end # end cluster

end # end configure
