{
 "title": "Kafka on Pulsar (KoP)",
 "tags": [ "KoP" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "{job=~\".+\"}"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "{instance =~\".+\", job=~\"$job\"}"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "{topic=~\".+\"}"
    }
   },
   {
    "name": "ApiKeys",
    "label": "ApiKeys",
    "query": {
     "query": "{request=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overviews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_MESSAGE_IN{job=~\"$job\"}[60s]))"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_MESSAGE_OUT{job=~\"$job\"}[60s]))"
    }
   ]
  },
  {
   "title": "Bytes in / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_BYTES_IN{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[60s]))"
    }
   ]
  },
  {
   "title": "Bytes out / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_BYTES_OUT{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[60s]))"
    }
   ]
  },
  {
   "title": "Request queue size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kop_server_REQUEST_QUEUE_SIZE{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Active channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kop_server_ACTIVE_CHANNEL_COUNT{job=~\"$job\"})"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Publish Latency - 50pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_PUBLISH{quantile=\"0.5\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_PUBLISH{quantile=\"0.99\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_PUBLISH{quantile=\"0.999\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Publish Latency - Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_PUBLISH{quantile=\"1.0\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Consume Latency - 50pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_READ{quantile=\"0.5\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Consume Latency - 99pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_READ{quantile=\"0.99\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Consume Latency - 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_READ{quantile=\"0.999\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Consume Latency - Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "kop_server_MESSAGE_READ{quantile=\"1.0\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Request metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active channel count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kop_server_ACTIVE_CHANNEL_COUNT{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Request queue size",
   "type": "graph",
   "description": "The number of quest in kop request processing queue of total request channel.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kop_server_REQUEST_QUEUE_SIZE{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Request latency count (success)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "kop_server_REQUEST_LATENCY_count{instance=~\"$instance\", job=~\"$job\", success=\"true\", request=~\"$ApiKeys\"}"
    }
   ]
  },
  {
   "title": "Request latency count (failed)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "kop_server_REQUEST_LATENCY_count{instance=~\"$instance\", job=~\"$job\", success=\"false\", request=~\"$ApiKeys\"}"
    }
   ]
  },
  { "title": "Producer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Message produce throughput (message/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_MESSAGE_IN{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[1m])"
    }
   ]
  },
  {
   "title": "Publish throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_BYTES_IN{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[1m])"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kop_server_BYTES_IN{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Produce message conversions time nanos",
   "type": "graph",
   "description": "The producer messages conversions in stats. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[1m])"
    }
   ]
  },
  { "title": "Consumer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Message consume throughput (message/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_MESSAGE_OUT{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[1m])"
    }
   ]
  },
  {
   "title": "Consume throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_BYTES_OUT{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}[1m])"
    }
   ]
  },
  {
   "title": "Consumer bytes out",
   "type": "graph",
   "description": "The consumer message out stats. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kop_server_BYTES_OUT{instance=~\"$instance\", job=~\"$job\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Consume message conversions time nanos",
   "type": "graph",
   "description": "The consumer message convert latency in nanoseconds. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{instance=~\"$instance\", job=~\"$job\", topic=~\"$topic\"}[1m])"
    }
   ]
  },
  { "title": "Kop event metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Event queue size",
   "type": "graph",
   "description": "The total number of events in KoP event processing queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kop_server_KOP_EVENT_QUEUE_SIZE{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Event latency",
   "type": "graph",
   "description": "The events processing total latency for all KoP event types. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kop_server_KOP_EVENT_LATENCY{instance=~\"$instance\", job=~\"$job\"}[1m])"
    }
   ]
  }
 ]
}