{
 "title": "Pulsar Detector",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "e2e failure count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pulsar_detector_e2e_latency_ms_count{success=\"false\"}-pulsar_detector_e2e_latency_ms_count{success=\"false\"} offset 5m)"
    }
   ]
  },
  {
   "title": "publish_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "e2e_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "pulsar_detector_e2e_latency_ms", "legendFormat": "{{ quantile }}" }
   ]
  }
 ]
}