{
 "title": "ZooKeeper",
 "description": "Metrics about ZooKeeper Service",
 "tags": [
  "zookeeper",
  "metadata"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "znode_count{job=~\".+\"}"
    }
   },
   {
    "name": "instance",
    "label": "zookeeper server",
    "query": {
     "query": "znode_count{job=~\"$job\", instance=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(znode_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "znode count"
    }
   ]
  },
  {
   "title": "watches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(watch_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ephemerals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ephemerals_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "data size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(approximate_data_size{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(num_alive_connections{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connection_request_count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "reads / s" }
   ],
   "targets": [
    {
     "expr": "connection_request_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Update Latency - 99pct",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "updatelatency{job=~\"$job\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read Latency - 99pct",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "readlatency{job=~\"$job\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_received{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Z-Nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "znode_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data set size",
   "type": "graph",
   "description": "Size of the data stored in a ZK server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of opened connections",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_alive_connections{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of watches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "watch_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of ephemerals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ephemerals_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}