---

- hosts: bookies
  become: yes
  gather_facts: false
  vars: 
    - fstype: ext4
  tasks:

    - name: mount bookie journal device
      mount:
        path: "{{ pulsar_bookie_journal_dir }}"
        src: "{{ bookie_journal_device }}"
        fstype: "{{ fstype }}"
        state: mounted
    - name: mount mount bookie ledgers device
      mount:
        path: "{{ pulsar_bookie_ledgers_dir }}"
        src: "{{ bookie_ledgers_device }}"
        fstype: "{{ fstype }}"
        state: mounted

