---

- hosts: bookies
  become: yes
  gather_facts: false
 
  vars: 
    - pulsar_dir: /opt/pulsar
    - pulsar_zk_data_dir: /opt/pulsar/data/zookeeper
    - pulsar_zk_txlog_dir: /opt/pulsar/data/zookeeper/txlog
    - pulsar_bookie_journal_dir: "{{ pulsar_dir }}/data/bookkeeper/journal-0"
    - pulsar_bookie_ledgers_dir: "{{ pulsar_dir }}/data/bookkeeper/ledgers-0"
    - pulsar_bookie_journal_dir1: "{{ pulsar_dir }}/data/bookkeeper/journal-1"
    - pulsar_bookie_ledgers_dir1: "{{ pulsar_dir }}/data/bookkeeper/ledgers-1" 
    - fstype: ext4
    - bookie_journal_device: /dev/disk/by-partlabel/journal-0
    - bookie_ledgers_device: /dev/disk/by-partlabel/ledgers-0
    - bookie_journal_device1: /dev/disk/by-partlabel/journal-1
    - bookie_ledgers_device1: /dev/disk/by-partlabel/ledgers-1    
  tasks:

    - name: mount bookie journal device
      mount:
        path: "{{ pulsar_bookie_journal_dir }}"
        src: "{{ bookie_journal_device }}"
        fstype: "{{ fstype }}"
        state: mounted

    - name: mount mount bookie ledgers device
      mount:
        path: "{{ pulsar_bookie_ledgers_dir }}"
        src: "{{ bookie_ledgers_device }}"
        fstype: "{{ fstype }}"
        state: mounted
    - name: mount bookie journal device1
      mount:
        path: "{{ pulsar_bookie_journal_dir1 }}"
        src: "{{ bookie_journal_device1 }}"
        fstype: "{{ fstype }}"
        state: mounted

    - name: mount mount bookie ledgers device1
      mount:
        path: "{{ pulsar_bookie_ledgers_dir1 }}"
        src: "{{ bookie_ledgers_device1 }}"
        fstype: "{{ fstype }}"
        state: mounted
