---

- hosts: zookeeper
  become: yes
  gather_facts: false
  vars:
    - fstype: ext4
    - pulsar_dir: /opt/pulsar
    - pulsar_zk_data_dir: /opt/pulsar/data/zookeeper
    - pulsar_zk_txlog_dir: /opt/pulsar/data/zookeeper/txlog
    - zk_data_device: /dev/disk/by-partlabel/zk-data
    - zk_txlog_device: /dev/disk/by-partlabel/zk-txlog
  tasks:

    - name: mount zk data device
      mount:
        path: "{{ pulsar_zk_data_dir }}"
        src: "{{ zk_data_device }}"
        fstype: "{{ fstype }}"
        state: mounted
        #state: present
    - name: mount zk txlog device
      mount:
        path: "{{ pulsar_zk_txlog_dir }}"
        src: "{{ zk_txlog_device }}"
        fstype: "{{ fstype }}"
        state: mounted
        #state: mounted

