---

- hosts: zookeeper
  become: yes
  gather_facts: false
  vars:
    - fstype: ext4
  tasks:

    - name: mount zk data device
      mount:
        path: "{{ pulsar_zk_data_dir }}"
        src: "{{ zk_data_device }}"
        fstype: "{{ fstype }}"
        state: mounted
    - name: mount zk txlog device
      mount:
        path: "{{ pulsar_zk_txlog_dir }}"
        src: "{{ zk_txlog_device }}"
        fstype: "{{ fstype }}"
        state: mounted

